version: '3.7'

services:
  db:
    build: ./db
    restart: always
    ports:
      - '5432:5432'
  backend:
    build: ./backend
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
